### PR TITLE
read and display vendor name and product name

### PR DESCRIPTION
**Pull request by edWin-m**
@pierredelisle This reads the `VendorName` and `ProductName` from the **Basic Information Cluster**.  The attribute values are displayed alongside the respective IDs in the `DeviceFragment`.  To some degree, it also resolves https://github.com/google-home/sample-app-for-matter-android/issues/35.

### CODE REVIEW

**Comment by pierredelisle** [comment]
Sorry for the delay reviewing. Will get to it today.

**Comment by pierredelisle** [comment]
Great work, thanks!
Only one thing, the changes to devices.proto will break backward compatibility. This is not a huge deal as this is just a demo application (and devs probably reset the app when installing a new version), but still, we like to show good practices. See https://protobuf.dev/programming-guides/proto3/#updating.

**Comment by edWin-m** [comment]
@pierredelisle Noted.  https://github.com/google-home/sample-app-for-matter-android/pull/137/commits/4d10a97cd75dc7988f4b86f383dc967a93b914bf addresses the backward compatibility issue. Feel free to let me know if there is anything I might have missed.

**Review by pierredelisle — APPROVED** [review]
All good. Thanks again.

**Comment by edWin-m** [comment]
Don't mention it.

**Pull request merged**
